title: Welcome
author: GitHub User
email: ogunjinmipeter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Peter Ogunjinmi is a PhD student at Intelligent Construction and Automation Center, Kyungpook National University, Daegu, South Korea.
  He has over 10 years experience in the Civil Engineering and Construction industry. His research interests include Structural Damage Identification, Disaster Response, 
  Computer Vision and Construction Automation. 
  Watch out for contents related to his research and academic adventures on this blog. 
  Kindly connect with him via his social media pages. You are welcome!

# social links
twitter_username: o_peter13 # DO NOT include the @ character, or else the build will fail!
github_username:  jimypeter # DO NOT include the @ character, or else the build will fail!
linkedin_username: peter-ogunjinmi
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
